### ISSUE TITLE
[Vssue]-[Comment]-再见WordPress，Hello Vuepress

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#151]
https://wiki.eryajf.net/pages/5be3f4/

**Comment by raymondelf** [comment]
👍👍👍持续关注博主，生产更多好文。🤞

**Comment by eryajf** [comment]
> @raymondelf
> 👍👍👍持续关注博主，生产更多好文。🤞

感谢支持，一定会坚持分享原创好文的！

**Comment by edisonwd** [comment]
看到大佬写的博客，特别佩服，自己也想写点东西，提笔满心话，落笔竟无言

**Comment by eryajf** [comment]
> @edisonwd
> 看到大佬写的博客，特别佩服，自己也想写点东西，提笔满心话，落笔竟无言

就像鲁迅先生说的随便看看那样，一开始可以先随便写写，其实写也是一个需要锻炼的能力，从写一些简记到短文，慢慢积攒就顺畅了⛽️

**Comment by yzqzss** [comment]
新博客的rss订阅链接是什么？没找到。

**Comment by eryajf** [comment]
> @yzqzss
> 新博客的rss订阅链接是什么？没找到。

目前还没有找到好用的订阅插件，后边遇到好的插件之后会添加rss支持。

**Comment by eryajf** [comment]
> @MikuSugar
> 博客写的很棒～
> > 这里时间是不是有点小问题
> ![b2N1mH](https://cdn.jsdelivr.net/gh/mikusugar/PictureBed@master/uPic/2021/08/b2N1mH.png)

谢谢，这里之前为了置顶这篇文章所以故意这么写了，后来了解到主题有置顶的参数，目前已修复此问题

**Comment by hsu1943** [comment]
再过些年，看你会不会喜欢上更简单化的风格，哈哈哈哈

**Comment by eryajf** [comment]
> @hsu1943
> 再过些年，看你会不会喜欢上更简单化的风格，哈哈哈哈

至少目前来看，vuepress深得我心，至于以后会不会换更简洁的，还真说不定

**Comment by penndu** [comment]
杜老师说祝福博主新春快乐！

**Comment by ACoach** [comment]
祝新年快乐。 奇怪文本框居然输入无效，我是Mac，只好别处写好了贴过来。希望有一天也能做个象这样的博客。

**Comment by eryajf** [comment]
> @ACoach
>   祝新年快乐。 奇怪文本框居然输入无效，我是Mac，只好别处写好了贴过来。希望有一天也能做个象这样的博客。

你是什么情况下输入无效的呢，我的评论回复都是在文本框里进行的呢，我也是Mac电脑。
你可以直接把我的源码克隆走，然后内容全部删除，慢慢积累出来一个自己的博客。
加油🥳

**Comment by ACoach** [comment]
就是Google Chrome页面的文本框输不进去。
我也很想把源代码都偷过来，不过不知道步骤如何。也不知道哪里摘源代码，实在很菜。

**Comment by ACoach** [comment]
评论还是不可以，当我输入一个字符后光标就移走了。有的时候会直接跑到页眉上面的搜索栏。

**Comment by eryajf** [comment]
> @yzqzss
> 新博客的rss订阅链接是什么？没找到。

现在，你可以通过 wiki.eryajf.net/rss.xml 进行订阅
