### ISSUE TITLE
[Vssue]-[Comment]-关于

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#152]
https://wiki.eryajf.net/about/

**Comment by eryajf** [comment]
这里是原 [eryajf.net](http://blog.eryajf.net) 博客的重构打造，新博客追求简单朴素的风格，尽可能把更多更好的内容呈现出来。

如果你有什么想法或者意见，欢迎在此沟通交流！

**Comment by xlqywk** [comment]
大佬，我能跟你做朋友吗

**Comment by xlqywk** [comment]
有没有微信或者ＱＱ群加一下，我QQ 48211701

**Comment by eryajf** [comment]
> @xlqywk
> 大佬，我能跟你做朋友吗

当然阔以哈！

**Comment by eryajf** [comment]
> @xlqywk
> 有没有微信或者ＱＱ群加一下，我QQ 48211701

OK，我加你，到时候加微信，还是习惯用微信

**Comment by SmartWrh** [comment]
大佬你好，您的Jenkins系列文章对我的帮助非常大，但是我碰到一个问题，在多分支流水线项目建成之后，具体到各分支的配置无法配置，不知可否指点一下，我的WX：WRH789456

**Comment by eryajf** [comment]
> @SmartWrh
> 大佬你好，您的Jenkins系列文章对我的帮助非常大，但是我碰到一个问题，在多分支流水线项目建成之后，具体到各分支的配置无法配置，不知可否指点一下，我的WX：WRH789456

OK，我加你，微信里沟通下你的问题

**Comment by onetwo12cn** [comment]
您好，感谢您的博客，收获颇多！

**Comment by eryajf** [comment]
> @onetwo12cn
> 您好，感谢您的博客，收获颇多！

感谢认可，欢迎常来

**Comment by LiuYu0537** [comment]
真的被这种坚持不懈的精神给震惊，还有才华，我会经常来学习！

**Comment by eryajf** [comment]
> @LiuYu0537
> 真的被这种坚持不懈的精神给震惊，还有才华，我会经常来学习！

同时被你的认可激励，欢迎常来学习监督，我也会坚持学习，记录，分享！

**Comment by 23095100** [comment]
对于这种大佬，我只能用四个字形容：才华横溢！

**Comment by eryajf** [comment]
> @23095100
> 对于这种大佬，我只能用四个字形容：才华横溢！

对于这种评论，我只能用四个字形容：完全赞同！

**Comment by Joyrocky** [comment]
大佬能提供一下周刊的全文RSS吗，收益匪浅

**Comment by eryajf** [comment]
> @Joyrocky
> 大佬能提供一下周刊的全文RSS吗，收益匪浅

有几种方式都可以对周刊进行订阅：

- 通过订阅本博客的RSS：https://wiki.eryajf.net/rss.xml
- 周刊有单独的仓库，可以关注该仓库：https://github.com/eryajf/learning-weekly
- 通过我的阅读列表进行关注：https://github.com/eryajf/read-list

**Comment by lanyiyun666** [comment]
您好，博主
可以投稿服务器或者scdn文章内容吗？
这边可以赞助高防scdn【国内外均可】【一年起】
并且会给您一个心意红包
国内正规持证公司

联合计划介绍：https://www.tsyvps.com/bbs/?p=158

如果不方便发您的联系方式

以下是我的联系方式！

我的QQ是：2814841448
