### ISSUE TITLE
[Vssue]-[Comment]-基于CNAME解析实践的域名优雅方案

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#154]
https://wiki.eryajf.net/pages/027a17/

**Comment by wendao365** [comment]
偶然间逛到这个博客，感觉真的很强，不是简单的写一些技术文章，有思考，有感悟，展现的是一个有血有肉的形象，希望向您请教一下这个网站是怎么搭建起来的。

**Comment by eryajf** [comment]
> @wendao365
> 偶然间逛到这个博客，感觉真的很强，不是简单的写一些技术文章，有思考，有感悟，展现的是一个有血有肉的形象，希望向您请教一下这个网站是怎么搭建起来的。

感谢你的肯定与支持🥳，欢迎常来逛，常来交流。
搭建其实非常简单，你可以通过右上角github点到博客的全部源码，然后fork到自己的仓库，克隆到本地之后，执行如下命令：

```
yarn
yarn dev
```

然后就可以在你本地将我的博客跑起来了。而后参考Vuepress的官方文档进行调整，就能搭建一个属于你自己的博客了！
