### ISSUE TITLE
[Vssue]-[Comment]-打嗝停不下来怎么办

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#168]
https://wiki.eryajf.net/pages/5369.html

**Comment by edisonwd** [comment]
通过憋气来缓解打嗝，这个方法我以前也试过，比较有效

**Comment by eryajf** [comment]
> @edisonwd
> 通过憋气来缓解打嗝，这个方法我以前也试过，比较有效

上次发烧又打嗝，非常离谱，非常难受，最后发现这些偏方，赶忙记录下来分享了
