### ISSUE TITLE
[Vssue]-[Comment]-冬晚小记

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#170]
https://wiki.eryajf.net/pages/567.html

**Comment by edisonwd** [comment]
从第一篇年终总结开始看，发现停不下来，想要一口气看完，发现你的文笔很好，一些日常小事都能描绘得十分深刻，怎样才能写出这样的文章呢？

**Comment by eryajf** [comment]
> @edisonwd
> 从第一篇年终总结开始看，发现停不下来，想要一口气看完，发现你的文笔很好，一些日常小事都能描绘得十分深刻，怎样才能写出这样的文章呢？

这是很早前写的文字，感谢肯定与支持，事实上之前还有不少的文章，以后应该会慢慢分享出来。
