### ISSUE TITLE
[Vssue]-[Comment]-Jenkins与gitlab的交互探微

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#186]
https://wiki.eryajf.net/pages/294.html

**Comment by WeilunFong** [comment]
第一种方法也适合单一分支发布，配合过滤器与浅克隆使用，作持续发布效率很高。把分支信息写死在shell里反而灵活性更差了，

**Comment by eryajf** [comment]
> @WeilunFong
> 第一种方法也适合单一分支发布，配合过滤器与浅克隆使用，作持续发布效率很高。把分支信息写死在shell里反而灵活性更差了，

是的，大多数都是使用的第一种方式的机制来与gitlab进行的交互
