### ISSUE TITLE
[Vssue]-[Comment]-配置gitlab提交代码Jenkins自动构建

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#207]
https://wiki.eryajf.net/pages/831.html

**Comment by gdwyz** [comment]
很多图片都看不了呀

**Comment by eryajf** [comment]
> @gdwyz
> 很多图片都看不了呀

可以强制刷新下再看看，现在图床用的自建图床，如果文章图片比较多，可以耐心等待下

**Comment by fxkjnj** [comment]
其实很多时候都是根据开发组长的merge动作，jenkins才会去自动构建，webhook指定的分支，有merge动作就自动构建

**Comment by eryajf** [comment]
> @fxkjnj
> 其实很多时候都是根据开发组长的merge动作，jenkins才会去自动构建，webhook指定的分支，有merge动作就自动构建

大多数场景中，我都不建议配置自动构建，会引入太多不稳定因素以及构建量过大的问题
