### ISSUE TITLE
[Vssue]-[Comment]-Jenkinsfile声明式语法详解

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#243]
https://wiki.eryajf.net/pages/3298.html

**Comment by eryajf** [comment]
通读这篇文，进入pipe门🥳，有任何疑问，可在评论区留言交流🤙

**Comment by zhushiyang** [comment]
像这样质量的文章真的不多，至少不用在频繁的搜索同样主题的内容就可以解决很多生产问题，很赞

**Comment by eryajf** [comment]
> @zhushiyang
> 像这样质量的文章真的不多，至少不用在频繁的搜索同样主题的内容就可以解决很多生产问题，很赞

感谢肯定，这篇文章整理的目的也是为了做成手册性质的，以便于用时查阅
