### ISSUE TITLE
[Vssue]-[Comment]-父亲写给我的高速行车注意事项

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#260]
https://wiki.eryajf.net/pages/2664.html

**Comment by edisonwd** [comment]
看到这些话语，感受到了那种深深的父爱与关切之情

**Comment by xlqywk** [comment]
一看老父亲就是知识渊博的人，懂的好多

**Comment by eryajf** [comment]
> @edisonwd
> 看到这些话语，感受到了那种深深的父爱与关切之情

看到您的评论，我也再次重读此文，再一次被父亲浓浓的爱意包裹
