### ISSUE TITLE
[Vssue]-[Comment]-使用Typora+坚果云（github）打造免费的个人云笔记

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#274]
https://wiki.eryajf.net/pages/2921.html

**Comment by moonlqer** [comment]
作者用什么图床工具？

**Comment by eryajf** [comment]
> @moonlqer
> 作者用什么图床工具？

本地写作图片放本地，博客图片放在自建图床了。用了一圈发现还是自建的比较稳妥靠谱，虽然速度慢了一点，但是稳定性有保障。
