### ISSUE TITLE
[Vssue]-[Comment]-使用PicGo+GitHub自建免费图床

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#275]
https://wiki.eryajf.net/pages/3022.html

**Comment by xuwillem** [comment]
图片上传成功咋办

**Comment by xuwillem** [comment]
图片上传不成功咋办

**Comment by eryajf** [comment]
> @xuwillem
> 图片上传不成功咋办

可以先检查一波配置是否有误，另外你上传不成功有没有什么错误提示呢

**Comment by aquamarineaqua** [comment]
> @xuwillem
> 图片上传不成功咋办

应该是设定分支名要写成 main，写master会报错

**Comment by eryajf** [comment]
> @aquamarineaqua
> > @xuwillem
> > 图片上传不成功咋办
> 
> 应该是设定分支名要写成 main，写master会报错

这个问题现在的确需要注意，我那时候配置默认分支还是master，现在变成main了
