### ISSUE TITLE
[Vssue]-[Comment]-vuepress编译时报错TypeError  _normalized undefined的解决

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#282]
https://wiki.eryajf.net/pages/32108f/

**Comment by Castleeee** [comment]
大佬我用的是vuepress-theme-reco，也出现了这个错误。  
我的文章只有三篇，dev不出错build就出错，但是build的结果是正常的。

**Comment by eryajf** [comment]
> @Castleeee
> 大佬我用的是vuepress-theme-reco，也出现了这个错误。  
> 我的文章只有三篇，dev不出错build就出错，但是build的结果是正常的。

所以你这里应该也不是文章数量的问题，而是文章所在的目录层级太多导致的吧，可以检查下你的项目里是否存在超过3级的目录。
