### ISSUE TITLE
[Vssue]-[Comment]-Prometheus邮件报警配置

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#472]
https://wiki.eryajf.net/pages/2475.html

**Comment by Study888** [comment]
实现了邮件报警

**Comment by eryajf** [comment]
> @Study888
> 实现了邮件报警  

后续可通过丰富告警规则，以及告警形式，将告警信息及时送达出来！

**Comment by Study888** [comment]
> @eryajf
> > @Study888
> > 实现了邮件报警  
> 
> 后续可通过丰富告警规则，以及告警形式，将告警信息及时送达出来！

对的 在网上有很多模板，修改下规则配置下告警模板可以清楚知道哪一台主机出现了什么问题

**Comment by qianzhiheyunwei** [comment]
Alertmanager启动不成功，只是修改了邮件的发件方与收件方，其他完美复制
