### ISSUE TITLE
[Vssue]-[Comment]-git-Parameter插件在pipeline共享库中的实践详解

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#569]
https://wiki.eryajf.net/pages/5328.html

**Comment by qiyue0421** [comment]
博主你好，我想询问关于Git Parameter插件的问题，使用流水线模式"Pipeline script from SCM"获取的总是jenkinsfile的分支，而不是项目的分支（jenkinsfile与项目不在同一仓库中），我该如何正确的使用这个插件呢

**Comment by eryajf** [comment]
> @qiyue0421
> 博主你好，我想询问关于Git Parameter插件的问题，使用流水线模式"Pipeline script from SCM"获取的总是jenkinsfile的分支，而不是项目的分支（jenkinsfile与项目不在同一仓库中），我该如何正确的使用这个插件呢

可以检查下，是不是你的useRepository这个参数，没有指向项目的地址，所以才会取了默认的Jenkinsfile的分支。

**Comment by qiyue0421** [comment]
gitParameter是否不支持流水线模式"Pipeline script from SCM"，我在插件官网没发现类似用法，

**Comment by eryajf** [comment]
> @qiyue0421
> gitParameter是否不支持流水线模式"Pipeline script from SCM"，我在插件官网没发现类似用法，

支持的，我上边开头举得例子，以及整篇文章都在讲这块儿的用法呀。

**Comment by qiyue0421** [comment]
我看了博主的这篇文章《git-Parameter插件在pipeline共享库中的实践详解》，我确实可以在流水线模式"Pipeline script"中实现它，但是好像不支持jenkinsfile脚本与项目分离的情况

![J0_%}}SQ(6FUVP%4Z@JKPBH](https://user-images.githubusercontent.com/33716216/144992218-b1979e66-0b34-4325-bd13-e38ddc366a4f.png)

图中我将jenkinsfile脚本拉取下来，脚本中有项目的仓库地址，在之前一般通过手动输入tag号进行构建，目前想实现自动获取项目的分支

**Comment by qiyue0421** [comment]
```
def initWorkspaces() {
    stage('Init Workspaces'){
        //定义参数，用来接收git parameter插件传递的值
        parameters {
            gitParameter name: 'BRANCH_TAG',
                         type: 'PT_BRANCH_TAG',
                         defaultValue: 'master'
        }
        cleanWs()
        //拉取指定分支或者标签的代码
        checkout([$class                           : 'GitSCM',
                  branches                         : [[name: "${params.BRANCH_TAG}"]],
                  doGenerateSubmoduleConfigurations: false,
                  extensions                       : [],
                  gitTool                          : 'Default',
                  //拉取子模块
                  extensions: [[
                                       $class: 'SubmoduleOption',
                                       disableSubmodules: false,
                                       parentCredentials: true,
                                       recursiveSubmodules: true,
                                       reference: '',
                                       trackingSubmodules: false
                               ]],
                  submoduleCfg                     : [],
                  userRemoteConfigs                : scm.userRemoteConfigs // ！重要，复用我们在 Jenkins 上 SCM 配置，如凭据、仓库地址
        ])
    }

}
```
![5LF(9ZE9}DD_`K53Z9FX 6O](https://user-images.githubusercontent.com/33716216/144996345-d1502f3d-0cca-434c-be18-0ec592fe62e4.png)


大佬我补充一下，这个配置文件适用于这种情况吧，直接是项目仓库中包含有jenkinsfile文件，这个验证成功了，如果jenkinsfile分离出去了，gitParameter还有办法吗
![J0_%}}SQ(6FUVP%4Z@JKPBH](https://user-images.githubusercontent.com/33716216/144996354-dd6a3428-96fb-4689-9358-cfd890cc66da.png)

**Comment by eryajf** [comment]
> @qiyue0421
> 我看了博主的这篇文章《git-Parameter插件在pipeline共享库中的实践详解》，我确实可以在流水线模式"Pipeline script"中实现它，但是好像不支持jenkinsfile脚本与项目分离的情况
> 
> ![J0_%}}SQ(6FUVP%4Z@JKPBH](https://user-images.githubusercontent.com/33716216/144992218-b1979e66-0b34-4325-bd13-e38ddc366a4f.png)
> 
> 图中我将jenkinsfile脚本拉取下来，脚本中有项目的仓库地址，在之前一般通过手动输入tag号进行构建，目前想实现自动获取项目的分支

这个截图里边的配置方式是对的，没有毛病，Jenkinsfile与项目仓库完全可以分离开。

**Comment by eryajf** [comment]
> @qiyue0421
> ```
> def initWorkspaces() {
>     stage('Init Workspaces'){
>         //定义参数，用来接收git parameter插件传递的值
>         parameters {
>             gitParameter name: 'BRANCH_TAG',
>                          type: 'PT_BRANCH_TAG',
>                          defaultValue: 'master'
>         }
>         cleanWs()
>         //拉取指定分支或者标签的代码
>         checkout([$class                           : 'GitSCM',
>                   branches                         : [[name: "${params.BRANCH_TAG}"]],
>                   doGenerateSubmoduleConfigurations: false,
>                   extensions                       : [],
>                   gitTool                          : 'Default',
>                   //拉取子模块
>                   extensions: [[
>                                        $class: 'SubmoduleOption',
>                                        disableSubmodules: false,
>                                        parentCredentials: true,
>                                        recursiveSubmodules: true,
>                                        reference: '',
>                                        trackingSubmodules: false
>                                ]],
>                   submoduleCfg                     : [],
>                   userRemoteConfigs                : scm.userRemoteConfigs // ！重要，复用我们在 Jenkins 上 SCM 配置，如凭据、仓库地址
>         ])
>     }
> 
> }
> ```
> ![5LF(9ZE9}DD_`K53Z9FX 6O](https://user-images.githubusercontent.com/33716216/144996345-d1502f3d-0cca-434c-be18-0ec592fe62e4.png)
> 
> 
> 大佬我补充一下，这个配置文件适用于这种情况吧，直接是项目仓库中包含有jenkinsfile文件，这个验证成功了，如果jenkinsfile分离出去了，gitParameter还有办法吗
> ![J0_%}}SQ(6FUVP%4Z@JKPBH](https://user-images.githubusercontent.com/33716216/144996354-dd6a3428-96fb-4689-9358-cfd890cc66da.png)
> 
> 

这里的代码写的不对，你先看我文中提供的例子，把GIT_URL改成你的git项目地址，然后把文件放到Jenkinsfile里边，再跑跑看就知道了。

**Comment by qiyue0421** [comment]
好的，非常感谢博主，我先测试一番

**Comment by qiyue0421** [comment]
博主你好，经过测试之后，最终结果还是显示的脚本的分支，我在你的代码上只修改了GIT_URL和CRED_ID参数

`pipeline {
    agent any
    environment {
        // 定义项目git地址
        GIT_URL="项目地址"
        CRED_ID = '7dbd6646-1fdf-441a-9017-deb71673718d'
    }

    parameters {
        gitParameter (branch:'', branchFilter: 'origin/(.*)', defaultValue: 'master', description: '选择将要构建的分支', name: 'BRANCH', quickFilterEnabled: true, selectedValue: 'TOP', sortMode: 'DESCENDING_SMART', tagFilter: '*', type: 'PT_BRANCH_TAG', useRepository: env.GIT_URL)
    }
    
    stages {
        stage('Example') {
            steps {
                checkout(
                    [$class: 'GitSCM', doGenerateSubmoduleConfigurations: false, submoduleCfg: [], extensions: [[$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true]],
                    branches: [[name: "$BRANCH"]],userRemoteConfigs: [[url: "${env.GIT_URL}", credentialsId: "${env.CRED_ID}"]]]
                )
            }
        }
    }
}`

![image](https://user-images.githubusercontent.com/33716216/145130175-747e9043-a89b-4e11-98c6-259401df9ffa.png)

**Comment by qiyue0421** [comment]
![image](https://user-images.githubusercontent.com/33716216/145134632-37d80bce-9f34-4a5d-9332-826e38b8dbe2.png)
博主博主，我按照上面这个配置成功获取了项目的分支号！！

![image](https://user-images.githubusercontent.com/33716216/145134740-68aaabb6-4861-4d78-bc5c-ad7b500800f2.png)

**Comment by qiyue0421** [comment]
是的，一般批量管理都是在jenkinsfile脚本中定义项目仓库地址的，不过在试过多种方法情况下，只有这样做才能获取到tag，再次感谢博主的耐心回复^-^
