### ISSUE TITLE
[Vssue]-[Comment]-我的Obsidian入门之旅

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#683]
https://wiki.eryajf.net/pages/6ed7fe/

**Comment by ACoach** [comment]
这是我见过的Timeline解说中最简单明了好懂的教程。 就是Templater，QuickAdd，加上Buttons的组合有点难。

**Comment by eryajf** [comment]
> @ACoach
> 这是我见过的Timeline解说中最简单明了好懂的教程。 就是Templater，QuickAdd，加上Buttons的组合有点难。

一般button与quickadd组合使用比较多一些，这里重点是quickadd的配置，quickadd配置好了之后，button基本上就是拷贝配置就能新建一个了。

**Comment by ACoach** [comment]
对的呢。我正在熟练中。
对了，我有个自己感觉很蠢的问题。就是在时间线里面使用图片有什么好办法，把本地图片弄上去吗？或者网上哪里可以上传本地图片？

**Comment by eryajf** [comment]
> @ACoach
> 对的呢。我正在熟练中。
> 对了，我有个自己感觉很蠢的问题。就是在时间线里面使用图片有什么好办法，把本地图片弄上去吗？或者网上哪里可以上传本地图片？
> 

如果你不熟悉图床怎么折腾，那我建议你可以先把图片放到本地一个固定的目录下。

**Comment by ACoach** [comment]
原来这东西叫图床啊，太感谢了。我把腾讯云搞定了，不过苹果电脑本地图床这个路径是怎么写，还没弄明白。

**Comment by eryajf** [comment]
> @ACoach
> 原来这东西叫图床啊，太感谢了。我把腾讯云搞定了，不过苹果电脑本地图床这个路径是怎么写，还没弄明白。

本地没有图床的概念，就是把图片直接放到ob某个目录下，然后引用图片的名字就可以了。

**Comment by stone3724** [comment]
hey，二丫你好，感谢你写的详细教程，想请教一个问题：比如我每天的日记都是用H1、H2等各种标签固定好的标准格式。 ##个人事项；##所思所想 之类。那么如果我在做月度或者年度总结的时候，想在一个页面中，将过去1年每一篇日记中 ##所思所想 的“内容”都提取出来，汇总在一起。这个问题困扰了很久，一直没找到合适的方法，Dataview只支持meta data的检索，不支持这类heading的检索，不知道你有没有什么好的思路可以指教？谢谢！
