### ISSUE TITLE
[Vssue]-[Comment]-vector实践-性能吊打logstash

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#742]
https://wiki.eryajf.net/pages/0322lius/

**Comment by zhanbei1** [comment]
你好，最近我也是在做logstash和vector的选型，但是我这边测试的处理性能，logstash要比vector高很多。测试场景：三个grok拆分 + 正则替换 + 重命名。使用的是标准的java的debug日志。所以针对于性能测试，想向你请教一下
