### ISSUE TITLE
[Vssue]-[Comment]-利用GitHub Actions自动将项目贡献者列表添加到README中

### ISSUE THREAD

**Issue by eryajf** [eryajf/eryajf.github.io#772]
https://wiki.eryajf.net/pages/2cb154/

**Comment by dr34-m** [comment]
GITHUB_TOKEN无需生成和配置，是Action自带，天生就有的

**Comment by dr34-m** [comment]
> @eryajf
> > @dr34-m
> >  GITHUB_TOKEN无需生成和配置，是Action自带，天生就有的
> 
> 具体的用法是啥样的呢，不是很理解

你可以看做github action默认帮你配置了一个`Repository secrets`，可以在yml文件中直接使用`${{ secrets.GITHUB_TOKEN }}`

**Comment by eryajf** [comment]
> @dr34-m
> > @eryajf
> > > @dr34-m
> > >  GITHUB_TOKEN无需生成和配置，是Action自带，天生就有的
> > 
> > 具体的用法是啥样的呢，不是很理解
> 
> 你可以看做github action默认帮你配置了一个`Repository secrets`，可以在yml文件中直接使用`${{ secrets.GITHUB_TOKEN }}`

OK，下次我试一试
