### ISSUE TITLE
大佬，IP需要隐藏吗~

### ISSUE THREAD

**Issue by arrheni** [eryajf/eryajf.github.io#950]
大佬您好，我是新手，感谢您的文章，学到了很多东西，不过在根目录
[sync.sh](https://github.com/eryajf/eryajf.github.io/blob/main/sync.sh)
泄露IP和端口啦，
```
 rsync -az -e 'ssh -p 2023' --delete docs/.vuepress/dist/  \
    root@8.136.215.57:/data/www/eryajf.github.io/
```

祝你开心

**Comment by eryajf** [comment]
通常不需要隐藏，公网IP本身本身就是可以对公的
